#pragma once
#include <iostream>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string>
#include <conio.h>
#include <array>
#include <cmath>
#include <ctime>
#include <time.h>
#include <chrono>
#include <Windows.h>
#include <fstream>
#include <istream>
#include <streambuf>
#include <sstream>

#include "mainInterface.h"
#include "DBABash.h"
#include "fortuneDataBase.h"